
# KanaBungeeTP V.1.3 Config File #

currentServerBungeeName: "server" # Server's name must be the same than proxy's config

database:
  host: '127.0.0.1'
  username: 'root'
  password: 'sqldevtest'
  port: '3306'
  name: 'test'

  tables:
    servers: "KBT_servers"